# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=90)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
