# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mundoDeportivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idEquipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEquipo', models.CharField(max_length=90)),
                ('tituloNoticia', models.CharField(max_length=200)),
                ('enlace', models.URLField()),
                ('noticia', models.CharField(max_length=700)),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='nombreEquipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundoDeportivo.Noticia'),
        ),
    ]
