# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mundoDeportivo', '0002_auto_20170101_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='idEquipo',
            new_name='idNoticia',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombreEquipo',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='nombreEquipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundoDeportivo.Equipo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='noticia',
            field=models.CharField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='tituloNoticia',
            field=models.CharField(max_length=600),
        ),
    ]
