# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundoDeportivo', '0005_noticia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(),
        ),
    ]
