# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundoDeportivo', '0006_auto_20170103_2019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registrado',
        ),
    ]
